export const APP_NAME = 'senna sound';
export const APP_DEFAULT_TITLE = 'Senna Sound';
export const APP_TITLE_TEMPLATE = '%s - Senna Sound';
export const APP_DESCRIPTION =
  'Discover unmatched precision, transparency, and control in our high-end preamplifier—perfect for powering stereo systems or enhancing home audio setups.';
export const APP_EMAIL = 'office@senna-sound.com';
export const KEYWORDS = [
  'Senna Sound',
  'high-fidelity audio',
  'audio amplifiers',
  'line preamplifiers',
  'power amplifiers',
  'phono preamplifiers',
  'premium audio',
  'precision sound',
  'audiophile equipment',
  'high-end audio systems',
  'Orca preamplifier',
  'Onyx power amplifier',
  'Phoenix phono stage',
  'analog sound',
  'MM and MC cartridges',
  'low distortion',
  'dynamic sound',
  'noise reduction',
  'clarity and transparency',
  'premium materials',
  'cutting-edge audio technology',
  'immersive sound experience',
  'amplifier design',
  'amplifier specifications',
  'RCA inputs',
  'audiophile-grade performance',
  'vinyl enthusiasts',
];
export const TAGS = [
  'Senna Sound',
  'high-fidelity audio',
  'audio equipment',
  'amplifiers',
  'preamplifiers',
  'power amplifiers',
  'phono amplifiers',
  'premium sound',
  'audiophile',
  'line preamplifier',
  'power amplifier',
  'phono stage',
  'analog audio',
  'vinyl',
  'audio',
  'MM cartridges',
  'MC cartridges',
  'distortion-free sound',
  'dynamic audio',
  'noise reduction',
  'precision audio',
  'home audio',
  'high-end audio',
  'audio technology',
  'sound quality',
  'luxury audio',
  'audiophile-grade',
];
